### ISSUE TITLE
Client must be run as root

### ISSUE THREAD

**Issue by djmaze** [3XX0/donkey#1]
When running `donkey get` as a non-root user, I get an empty output and the server outputs `could not establish connection: Operation not permitted`. 

I spent some time figuring out you are using [abstract sockets](http://blog.eduardofleury.com/archives/2007/09/13). As they [don't have permissions](https://utcc.utoronto.ca/~cks/space/blog/linux/SocketAbstractNamespace), it is possible for other users to read the secret. A short paragraph explaining how this tool works (and the drawbacks) would be nice.

**Comment by 3XX0** [comment]
Yes it definitely needs more documentation, I will try to add some when I find some time.

As you mentioned, `donkey` won't allow non-root users to retrieve the key for security reasons. Maybe we could have an option to relax this requirement, another way would be to check the PID of `docker build` but it's a little tricky to do.

**Comment by 3XX0** [comment]
I added a short summary in the README
